name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y                 build-essential git zip unzip curl openjdk-17-jdk                 automake autoconf libtool pkg-config python3.10-dev

      - name: Install pip & tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install "Cython==0.29.36" "buildozer==1.5.0" "python-for-android==2024.1.21" "kivy==2.2.1"

      - name: Build APK (debug)
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROIDAPI: "31"
          ANDROIDMINAPI: "21"
        run: |
          yes | buildozer -v android debug apk
          ls -lah bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Demo-APK
          path: bin/*.apk
          if-no-files-found: error
